compilation errors check before run

diff --git a/.cirrus.yml b/.cirrus.yml
--- a/.cirrus.yml
+++ b/.cirrus.yml
@@ -36,6 +36,18 @@ linux_task:
         SANITIZE: true
 
   build_script:
+    - CXX=${COMPILER} CXXFLAGS=${CXXFLAGS} ./check_errors.sh || {
+        FAILURES="$?" ;
+        if [[ ${CXX_STANDARD} == "11" ]]; then
+          if [[ ${FAILURES} != "4" ]]; then
+            echo "Expected four failures from C++11 check_errors.sh, got ${FAILURES}" ;
+            exit 1 ;
+          fi ;
+        else
+          echo "Expected zero failures from check_errors.sh, got ${FAILURES}" ;
+          exit 1 ;
+        fi ;
+      }
     - mkdir build
     - cd build
     - CXX=${COMPILER} cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_EXE_LINKER_FLAGS="${LDFLAGS}" -DCMAKE_CXX_STANDARD=${CXXSTD} -DCXX_STDLIB=${STDLIB} -DSANITIZE=${SANITIZE} ..
